/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Marcio
 */
public class TelaMapa extends javax.swing.JFrame {

    /**
     * Creates new form TelaMapa
     */
    public TelaMapa() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCidade9 = new javax.swing.JLabel();
        uJPanelImagem2 = new componentes.UJPanelImagem();
        jlCidade0 = new javax.swing.JLabel();
        jlCidade1 = new javax.swing.JLabel();
        jlCidade2 = new javax.swing.JLabel();
        jlCidade3 = new javax.swing.JLabel();
        jlCidade4 = new javax.swing.JLabel();
        jlCidade5 = new javax.swing.JLabel();
        jlCidade6 = new javax.swing.JLabel();
        jlCidade7 = new javax.swing.JLabel();
        jlCidade8 = new javax.swing.JLabel();
        jlOrigem = new javax.swing.JLabel();
        jlDestino = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jbProfundidade = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbLargura = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbCaminhoMinimo = new javax.swing.JButton();
        jlCaminhoMinimo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jlCidade9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade9.setText("Santos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uJPanelImagem2.setImagem(new java.io.File("C:\\Program Files\\NetBeans 8.0\\Imagens\\mapaBase.png"));

        jlCidade0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade0.setText("Araraquara");

        jlCidade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade1.setText("Araçatuba");

        jlCidade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade2.setText("Bauru");

        jlCidade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade3.setText("Campinas");

        jlCidade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade4.setText("Marilia");

        jlCidade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade5.setText("Piracicaba");

        jlCidade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade6.setText("Santos");

        jlCidade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade7.setText("Sorocaba");

        jlCidade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vertice03.png"))); // NOI18N
        jlCidade8.setText("Presidente Prudente");

        javax.swing.GroupLayout uJPanelImagem2Layout = new javax.swing.GroupLayout(uJPanelImagem2);
        uJPanelImagem2.setLayout(uJPanelImagem2Layout);
        uJPanelImagem2Layout.setHorizontalGroup(
            uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jlCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jlCidade1))
                    .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jlCidade4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem2Layout.createSequentialGroup()
                        .addComponent(jlCidade0)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem2Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCidade6)
                            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                                .addComponent(jlCidade7)
                                .addGap(32, 32, 32)
                                .addComponent(jlCidade3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(139, 139, 139))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlCidade5)
                .addGap(233, 233, 233))
            .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jlCidade8)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );
        uJPanelImagem2Layout.setVerticalGroup(
            uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jlCidade1)
                .addGap(45, 45, 45)
                .addComponent(jlCidade0)
                .addGap(18, 18, 18)
                .addComponent(jlCidade4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCidade2)
                .addGap(2, 2, 2)
                .addComponent(jlCidade5)
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCidade3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCidade7))
                .addGap(27, 27, 27)
                .addComponent(jlCidade6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(jlCidade8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );

        jlOrigem.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlOrigem.setForeground(new java.awt.Color(255, 0, 51));
        jlOrigem.setText("Origem:");

        jlDestino.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlDestino.setForeground(new java.awt.Color(0, 0, 255));
        jlDestino.setText("Destino:");
        jlDestino.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbProfundidade.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbProfundidade.setText("Simular Busca Profundidade");

        jButton1.setText("jButton1");

        jbLargura.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbLargura.setText("Simular Busca Largura");

        jbLimpar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbLimpar.setText("Limpar Mapa");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbCaminhoMinimo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbCaminhoMinimo.setText("Caminho Minimo");

        jlCaminhoMinimo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlCaminhoMinimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("KM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCaminhoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jlCaminhoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbCaminhoMinimo)
                .addGap(26, 26, 26)
                .addComponent(jlCaminhoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(86, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jlOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 121, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(285, 285, 285))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbProfundidade))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(uJPanelImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(uJPanelImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(467, 467, 467)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlOrigem)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlDestino)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jbProfundidade)
                                .addGap(21, 21, 21)
                                .addComponent(jbLargura)
                                .addGap(20, 20, 20)
                                .addComponent(jbLimpar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCaminhoMinimo;
    private javax.swing.JButton jbLargura;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbProfundidade;
    private javax.swing.JLabel jlCaminhoMinimo;
    private javax.swing.JLabel jlCidade0;
    private javax.swing.JLabel jlCidade1;
    private javax.swing.JLabel jlCidade2;
    private javax.swing.JLabel jlCidade3;
    private javax.swing.JLabel jlCidade4;
    private javax.swing.JLabel jlCidade5;
    private javax.swing.JLabel jlCidade6;
    private javax.swing.JLabel jlCidade7;
    private javax.swing.JLabel jlCidade8;
    private javax.swing.JLabel jlCidade9;
    private javax.swing.JLabel jlDestino;
    private javax.swing.JLabel jlOrigem;
    private componentes.UJPanelImagem uJPanelImagem2;
    // End of variables declaration//GEN-END:variables
}
